set_datetime:
  description: This can be used to dynamically set the date and/or time. Use date/time, datetime or timestamp.
  fields:
    entity_id:
      description: Entity id of the input datetime to set the new value.
      example: input_datetime.test_date_time
    date:
      description: The target date the entity should be set to.
      example: '"2019-04-20"'
    time:
      description: The target time the entity should be set to.
      example: '"05:04:20"'
    datetime:
      description: The target date & time the entity should be set to.
      example: '"2019-04-20 05:04:20"'
    timestamp:
      description: The target date & time the entity should be set to as expressed by a UNIX timestamp.
      example: 1598027400

reload:
  description: Reload the input_datetime configuration.
